<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="acorn">

    <!-- <xacro:include filename="robot_core.xacro" /> -->

    <!-- REFER TO IMAGES FOLDER FOR VISUAL REPRESENTATION OF THE ROBOT -->
    <xacro:include filename="wheel_module_macro.xacro" />
    <xacro:include filename="color_macro.xacro" />
    <xacro:include filename="inertia_macro.xacro" />

    <!-- CONSTANTS -->
    <xacro:property name="PI" value="3.1415926535897931"/>
    <!-- <xacro:arg name="is_simulation" default="true" /> -->

    <!-- Chassis dimensions -->
    <xacro:property name="chassis_mass" value="30.0"/> <!-- kilograms -->
    <xacro:property name="chassis_length" value="2"/> <!-- meters -->
    <xacro:property name="chassis_width" value="2"/>
    <xacro:property name="chassis_height" value="0.3"/>

    <!-- Wheel Module dimensions -->
    <xacro:property name="base_to_module_x" value="0.8"/> <!-- meters -->
    <xacro:property name="base_to_module_y" value="0.8"/>
    <xacro:property name="module_width_x" value="0.2"/>
    <xacro:property name="module_width_y" value="0.15"/>
    <xacro:property name="module_height" value="0.8"/>

    <!-- Wheel dimensions -->
    <xacro:property name="wheel_mass" value="5.0"/> <!-- kilograms -->
    <xacro:property name="wheel_radius" value="0.3"/> <!-- meters -->
    <xacro:property name="wheel_width" value="0.1"/>

    <!-- Define a base links for the robot. base_link and base_footprint needed for Nav2 -->
    <link name="base_footprint"/>

    <joint name="base_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0 0 ${module_height + wheel_radius}" rpy="0 0 0"/>
    </joint>

    <link name="base_link"/>

    <!-- Define a chassis link for the robot -->
    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <!-- Place the chassis at half of chassis height above the base link -->
        <origin xyz="0 0 ${chassis_height/2.0}" rpy="0 0 0"/>
    </joint>

    <link name="chassis">
        <visual>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <material name="grey"/>
        </visual>
        <collision>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="${chassis_mass}" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <!-- Define joints to connect static links to the base link -->
    <joint name="FL_joint" type="fixed">
        <parent link="base_link"/>
        <child link="front_left"/>
        <origin xyz="${base_to_module_x} ${base_to_module_y} 0" rpy="0 0 0"/>
    </joint>

    <joint name="FR_joint" type="fixed">
        <parent link="base_link"/>
        <child link="front_right"/>
        <origin xyz="${base_to_module_x} -${base_to_module_y} 0" rpy="0 0 0"/>
    </joint>

    <joint name="RL_joint" type="fixed">
        <parent link="base_link"/>
        <child link="rear_left"/>
        <origin xyz="-${base_to_module_x} ${base_to_module_y} 0" rpy="0 0 0"/>
    </joint>

    <joint name="RR_joint" type="fixed">
        <parent link="base_link"/>
        <child link="rear_right"/>
        <origin xyz="-${base_to_module_x} -${base_to_module_y} 0" rpy="0 0 0"/>
    </joint>

    <!-- Define 4 static links which will be used to connect the wheel modules to the base link -->
    <link name="front_left">
    </link>
    <link name="front_right">
    </link>
    <link name="rear_left">
    </link>
    <link name="rear_right">
    </link>

    <!-- Define the wheel modules -->
    <!-- params="parent_name mass radius width module_len module_width_x module_width_y cx cy cz side" -->
    <!-- NOTE: cx,cy,cz are the coordinates of the child link's center w.r.t the parent link -->
    <xacro:wheel_assembly parent_name="front_left" mass="${wheel_mass}" radius="${wheel_radius}" width="${wheel_width}" module_len="${module_height}" module_width_x="${module_width_x}" module_width_y="${module_width_y}" cx="0" cy="0" cz="${-module_height/2.0}" side="left"/>
    <xacro:wheel_assembly parent_name="front_right" mass="${wheel_mass}" radius="${wheel_radius}" width="${wheel_width}" module_len="${module_height}" module_width_x="${module_width_x}" module_width_y="${module_width_y}" cx="0" cy="0" cz="${-module_height/2.0}" side="right"/>
    <xacro:wheel_assembly parent_name="rear_left" mass="${wheel_mass}" radius="${wheel_radius}" width="${wheel_width}" module_len="${module_height}" module_width_x="${module_width_x}" module_width_y="${module_width_y}" cx="0" cy="0" cz="${-module_height/2.0}" side="left"/>
    <xacro:wheel_assembly parent_name="rear_right" mass="${wheel_mass}" radius="${wheel_radius}" width="${wheel_width}" module_len="${module_height}" module_width_x="${module_width_x}" module_width_y="${module_width_y}" cx="0" cy="0" cz="${-module_height/2.0}" side="right"/>

    <!-- IMU temporarily placed 5cm above base link -->
    <joint name="imu_joint" type="fixed">
        <parent link="base_link"/>
        <child link="imu_link"/>
        <origin xyz="0.0 0.0 ${chassis_height/3}" rpy="0 0 0"/>
    </joint>

    <link name="imu_link"/>

    <!-- GPS link at base link -->
    <joint name="gps_joint" type="fixed">
        <parent link="base_link"/>
        <child link="gps_link"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="gps_link">
        <inertial>
            <mass>0.001</mass>
            <ixx>0.001</ixx>
            <ixy>0.000</ixy>
            <ixz>0.000</ixz>
            <iyy>0.001</iyy>
            <iyz>0.000</iyz>
            <izz>0.001</izz>
        </inertial>
    </link>

    <!-- 2D Lidar placed in front center 20cm below chassis-->
    <joint name="scan_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_scan"/>
        <origin xyz="${chassis_length/2} 0 -0.2" rpy="0 0 0"/>
    </joint>

    <link name="base_scan">
        <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <mesh filename="package://turtlebot3_gazebo/models/turtlebot3_common/meshes/lds.dae" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="dark"/>
        </visual>

        <collision>
        <origin xyz="0.015 0 -0.0065" rpy="0 0 0"/>
        <geometry>
            <cylinder length="0.0315" radius="0.055"/>
        </geometry>
        </collision>

        <inertial>
        <mass value="0.114" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.001" ixy="0.0" ixz="0.0"
                iyy="0.001" iyz="0.0"
                izz="0.001" />
        </inertial>
    </link>

    <!-- Include gazebo macros for sim -->
    <xacro:include filename="gazebo.xacro" />

</robot>
