version: '3'
services:
  ddg-humble-container:
    build:
      context: .
      dockerfile: dockerfile/Dockerfile
    image: twisted-humblesim:latest
    container_name: twisted-humble-container
    privileged: true
    hostname: twisted-humble-container
    restart: always
    stdin_open: true
    tty: true
    network_mode: "host"
    dns:
      - 1.1.1.1
      - 1.0.0.1
      - 8.8.8.8
    environment:
      - "DISPLAY"
      - "NVIDIA_VISIBLE_DEVICES=all"
      - "NVIDIA_DRIVER_CAPABILITIES=all"
      - "FASTRTPS_DEFAULT_PROFILES_FILE=/usr/local/share/middleware_profiles/rtps_udp_profile.xml"
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "${HOME}/.Xauthority:/home/admin/.Xauthority:rw"
      - "${PWD}/../:/home/admin/"
      - "/dev/*:/dev/*"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
